services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
      - GITEA__server__PROTOCOL=https
      - GITEA__server__CERT_FILE=/data/cert.pem
      - GITEA__server__KEY_FILE=/data/key.pem
      - GITEA__server__DOMAIN=gitea
      - GITEA__server__ROOT_URL=https://gitea:3000/
      - GITEA__server__DISABLE_SSH=true
      - TZ=America/Chicago
    restart: always
    volumes:
      - ./gitea:/data
      - ./cert.pem:/data/cert.pem:ro
      - ./key.pem:/data/key.pem:ro
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - gitea_net

  runner:
    image: gitea/act_runner:latest
    container_name: gitea_runner
    restart: always
    volumes:
      - ./runner:/data
      - /run/podman/podman.sock:/var/run/docker.sock
      - ./cert.pem:/usr/local/share/ca-certificates/gitea.crt:ro
      - ./cert.pem:/etc/ssl/certs/gitea.crt:ro
      - ./runner-config.yaml:/data/config.yaml:ro
      - ./cert.pem:${PWD}/cert.pem:ro
    environment:
      - GITEA_INSTANCE_URL=https://gitea:3000
      - GITEA_RUNNER_REGISTRATION_TOKEN=${GITEA_RUNNER_TOKEN}
      - GITEA_RUNNER_NAME=podman-runner
      - SSL_CERT_FILE=/usr/local/share/ca-certificates/gitea.crt
      - NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/gitea.crt
      - CURL_CA_BUNDLE=/usr/local/share/ca-certificates/gitea.crt
      - PWD=${PWD}
    depends_on:
      - gitea
    networks:
      - gitea_net

  db:
    image: postgres:15
    container_name: gitea_db
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - gitea_net

volumes:
  gitea:
  postgres:

networks:
  gitea_net:
